# Generated by Django 5.2.9 on 2025-12-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('LUZ', 'Luz'), ('AGUA', 'Agua'), ('TELEFONO', 'Teléfono'), ('INTERNET', 'Internet'), ('GAS', 'Gas Domiciliario'), ('ASEO', 'Tasa de Aseo'), ('CUENTA', 'Cuenta Bancaria')], max_length=100),
        ),
    ]
